### ISSUE TITLE
The VMess protocol is always sent.

### ISSUE THREAD

**Issue by hawshemi** [vfarid/v2ray-worker#1]
Thanks for your great work! good job.

I think there is a bug with the `VMESS` part. because no matter what the settings are, the `VMess` configs are always in the sub list.
for example, I only select `VLess` but at least 100 configs are `VMess` and the rest are `VLess`. Also for `Trojan` and `SS`.

**Comment by vfarid** [comment]
When you check "Include merged configs", 50% of configs will be merged VMESS configs. If you dont want those configs, simply uncheck the box.

**Comment by hawshemi** [comment]
Correct, but when I uncheck the box, no `VLess` configs are sent.
Is it from the providers who didn't provide any `VLess` or smth else?
