### ISSUE TITLE
errore

### ISSUE THREAD

**Issue by Ahmadjafari200** [vfarid/v2ray-worker#11]
[{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'buffer' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 252,
	"startColumn": 21,
	"endLineNumber": 252,
	"endColumn": 27
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'byteOffset' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 260,
	"startColumn": 21,
	"endLineNumber": 260,
	"endColumn": 31
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2345",
	"severity": 8,
	"message": "Argument of type 'string' is not assignable to parameter of type 'number'.",
	"source": "ts",
	"startLineNumber": 338,
	"startColumn": 77,
	"endLineNumber": 338,
	"endColumn": 85
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'write' does not exist on type 'Uint8Array'.",
	"source": "ts",
	"startLineNumber": 364,
	"startColumn": 26,
	"endLineNumber": 364,
	"endColumn": 31
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 622,
	"startColumn": 24,
	"endLineNumber": 622,
	"endColumn": 30
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 632,
	"startColumn": 24,
	"endLineNumber": 632,
	"endColumn": 30
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 643,
	"startColumn": 24,
	"endLineNumber": 643,
	"endColumn": 30
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 656,
	"startColumn": 27,
	"endLineNumber": 656,
	"endColumn": 33
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 675,
	"startColumn": 16,
	"endLineNumber": 675,
	"endColumn": 22
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 701,
	"startColumn": 24,
	"endLineNumber": 701,
	"endColumn": 30
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 703,
	"startColumn": 79,
	"endLineNumber": 703,
	"endColumn": 85
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 891,
	"startColumn": 23,
	"endLineNumber": 891,
	"endColumn": 29
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 895,
	"startColumn": 23,
	"endLineNumber": 895,
	"endColumn": 29
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 912,
	"startColumn": 30,
	"endLineNumber": 912,
	"endColumn": 36
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 915,
	"startColumn": 76,
	"endLineNumber": 915,
	"endColumn": 82
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property '_arr' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 950,
	"startColumn": 47,
	"endLineNumber": 950,
	"endColumn": 51
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1073,
	"startColumn": 24,
	"endLineNumber": 1073,
	"endColumn": 30
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'subarray' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1092,
	"startColumn": 27,
	"endLineNumber": 1092,
	"endColumn": 35
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1106,
	"startColumn": 47,
	"endLineNumber": 1106,
	"endColumn": 53
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1119,
	"startColumn": 47,
	"endLineNumber": 1119,
	"endColumn": 53
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1131,
	"startColumn": 37,
	"endLineNumber": 1131,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1137,
	"startColumn": 37,
	"endLineNumber": 1137,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1143,
	"startColumn": 37,
	"endLineNumber": 1143,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1149,
	"startColumn": 37,
	"endLineNumber": 1149,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1155,
	"startColumn": 37,
	"endLineNumber": 1155,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1186,
	"startColumn": 47,
	"endLineNumber": 1186,
	"endColumn": 53
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1202,
	"startColumn": 47,
	"endLineNumber": 1202,
	"endColumn": 53
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1217,
	"startColumn": 37,
	"endLineNumber": 1217,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1225,
	"startColumn": 37,
	"endLineNumber": 1225,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1232,
	"startColumn": 37,
	"endLineNumber": 1232,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1239,
	"startColumn": 37,
	"endLineNumber": 1239,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1245,
	"startColumn": 37,
	"endLineNumber": 1245,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1273,
	"startColumn": 37,
	"endLineNumber": 1273,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1279,
	"startColumn": 37,
	"endLineNumber": 1279,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1285,
	"startColumn": 37,
	"endLineNumber": 1285,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1291,
	"startColumn": 37,
	"endLineNumber": 1291,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1566,
	"startColumn": 20,
	"endLineNumber": 1566,
	"endColumn": 26
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1575,
	"startColumn": 39,
	"endLineNumber": 1575,
	"endColumn": 45
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1580,
	"startColumn": 38,
	"endLineNumber": 1580,
	"endColumn": 44
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1584,
	"startColumn": 22,
	"endLineNumber": 1584,
	"endColumn": 28
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1585,
	"startColumn": 20,
	"endLineNumber": 1585,
	"endColumn": 26
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'copyWithin' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1591,
	"startColumn": 14,
	"endLineNumber": 1591,
	"endColumn": 24
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'subarray' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1595,
	"startColumn": 16,
	"endLineNumber": 1595,
	"endColumn": 24
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1606,
	"startColumn": 22,
	"endLineNumber": 1606,
	"endColumn": 28
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1609,
	"startColumn": 22,
	"endLineNumber": 1609,
	"endColumn": 28
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1628,
	"startColumn": 29,
	"endLineNumber": 1628,
	"endColumn": 35
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1628,
	"startColumn": 52,
	"endLineNumber": 1628,
	"endColumn": 58
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'Buffer5'.",
	"source": "ts",
	"startLineNumber": 1635,
	"startColumn": 35,
	"endLineNumber": 1635,
	"endColumn": 41
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2552",
	"severity": 8,
	"message": "Cannot find name 'url'. Did you mean 'URL'?",
	"source": "ts",
	"startLineNumber": 2698,
	"startColumn": 41,
	"endLineNumber": 2698,
	"endColumn": 44,
	"relatedInformation": [
		{
			"startLineNumber": 1791,
			"startColumn": 15,
			"endLineNumber": 1791,
			"endColumn": 18,
			"message": "'URL' is declared here.",
			"resource": "/sabun/workers-types.d.ts"
		}
	]
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.",
	"source": "ts",
	"startLineNumber": 2770,
	"startColumn": 13,
	"endLineNumber": 2770,
	"endColumn": 30
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'captureStackTrace' does not exist on type 'ErrorConstructor'.",
	"source": "ts",
	"startLineNumber": 2771,
	"startColumn": 11,
	"endLineNumber": 2771,
	"endColumn": 28
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'loadKind' does not exist on type 'Type$1'.",
	"source": "ts",
	"startLineNumber": 2978,
	"startColumn": 16,
	"endLineNumber": 2978,
	"endColumn": 24
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'loadKind' does not exist on type 'Type$1'.",
	"source": "ts",
	"startLineNumber": 2978,
	"startColumn": 35,
	"endLineNumber": 2978,
	"endColumn": 43
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'implicit' does not exist on type 'Schema$1'.",
	"source": "ts",
	"startLineNumber": 2991,
	"startColumn": 27,
	"endLineNumber": 2991,
	"endColumn": 35
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'explicit' does not exist on type 'Schema$1'.",
	"source": "ts",
	"startLineNumber": 2992,
	"startColumn": 27,
	"endLineNumber": 2992,
	"endColumn": 35
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2554",
	"severity": 8,
	"message": "Expected 1 arguments, but got 2.",
	"source": "ts",
	"startLineNumber": 3242,
	"startColumn": 35,
	"endLineNumber": 3242,
	"endColumn": 37
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type 'string' is not assignable to type 'number'.",
	"source": "ts",
	"startLineNumber": 3332,
	"startColumn": 5,
	"endLineNumber": 3332,
	"endColumn": 13
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'length' does not exist on type 'number'.",
	"source": "ts",
	"startLineNumber": 3333,
	"startColumn": 21,
	"endLineNumber": 3333,
	"endColumn": 27
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2322",
	"severity": 8,
	"message": "Type 'string' is not assignable to type 'number'.",
	"source": "ts",
	"startLineNumber": 3334,
	"startColumn": 7,
	"endLineNumber": 3334,
	"endColumn": 15
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'push' does not exist on type 'any[] | {}'.\n  Property 'push' does not exist on type '{}'.",
	"source": "ts",
	"startLineNumber": 4070,
	"startColumn": 15,
	"endLineNumber": 4070,
	"endColumn": 19
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'push' does not exist on type 'any[] | {}'.\n  Property 'push' does not exist on type '{}'.",
	"source": "ts",
	"startLineNumber": 4072,
	"startColumn": 15,
	"endLineNumber": 4072,
	"endColumn": 19
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'dump' does not exist on type 'State'.",
	"source": "ts",
	"startLineNumber": 5327,
	"startColumn": 18,
	"endLineNumber": 5327,
	"endColumn": 22
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "18047",
	"severity": 8,
	"message": "'conf' is possibly 'null'.",
	"source": "ts",
	"startLineNumber": 5516,
	"startColumn": 18,
	"endLineNumber": 5516,
	"endColumn": 22
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "18047",
	"severity": 8,
	"message": "'conf' is possibly 'null'.",
	"source": "ts",
	"startLineNumber": 5527,
	"startColumn": 17,
	"endLineNumber": 5527,
	"endColumn": 21
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "18047",
	"severity": 8,
	"message": "'conf' is possibly 'null'.",
	"source": "ts",
	"startLineNumber": 5529,
	"startColumn": 19,
	"endLineNumber": 5529,
	"endColumn": 23
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "18047",
	"severity": 8,
	"message": "'conf' is possibly 'null'.",
	"source": "ts",
	"startLineNumber": 5529,
	"startColumn": 33,
	"endLineNumber": 5529,
	"endColumn": 37
},{
	"resource": "/sabun/worker.js",
	"owner": "typescript",
	"code": "2339",
	"severity": 8,
	"message": "Property 'name' does not exist on type '{ url: any; count: number; configs: any; mergedConfigs: any; }'.",
	"source": "ts",
	"startLineNumber": 5648,
	"startColumn": 103,
	"endLineNumber": 5648,
	"endColumn": 107
}]

**Comment by vfarid** [comment]
شما احتمالا کد رو ناقص کپی کرده بودید. چنین خطایی در حالت کلی وجود نداره.
