### ISSUE TITLE
با ورزن 2.2 لینک کدها را نمی اورد

### ISSUE THREAD

**Issue by asna220** [vfarid/v2ray-worker#19]
با سلام 
تمام مراحل انجام شد .
لینک را داخل وی تو ری می زنیم آپدیت نمی کند حتی در حالت متصل بودن وی پی ان  و هیچ کدی اضافه نمی کند.
با تشکر

**Comment by vfarid** [comment]
این موضوع و روش رفع مشکل رو تو منشن‌های توییتم نوشتم. شما جایی رو حتما اشتباه کردید و کد فعال نشده. برای تست پنل و لینک ساب رو در بروزر بزنید و خروجی رو ببینید. وقتی که خروجی درست بود بعد ساب رو در کلاینت v2ray آپدیت کنید.
