### ISSUE TITLE
توی v2rayn توی مخابرات کار نمیکنه اصلا  پینگ نمیده

### ISSUE THREAD

**Issue by wolfkingal2000** [vfarid/v2ray-worker#20]
سلام توی v2rayn توی مخابرات کار نمیکنه اصلا  پینگ نمیده ولی توی گوشی v2rayng کار میکنه ولی توی دسکتاپ و مخابرات نه مشکلش چیه؟ همون طور که ویدویی گفته‌بود انجامش داد

**Comment by GetPHP-IR** [comment]
> > > سلام توی v2rayn توی مخابرات کار نمیکنه اصلا پینگ نمیده ولی توی گوشی v2rayng کار میکنه ولی توی دسکتاپ و مخابرات نه مشکلش چیه؟ همون طور که ویدویی گفته‌بود انجامش داد
> > 
> > 
> > من با nekoray مخابرات و همراه اول و ایرانسل تست کردم اوکی بود
> 
> با اون هم تست کردم اصلا نمیده پینگی

پس از نت شماست، یکم سرعتش کمه و پینگش زیاده ولی به هر حال کار میکنه

**Comment by vfarid** [comment]
در پانل کنترل از اسکنر تغبیه شده استفاده کنید، آی‌پی تمیز پیدا کنید و داخل پنل وارد کنید. بعد sub رو آپدیت کنید، فعال میشن کانفیگ‌ها.
