### ISSUE TITLE
Bug: Resource Limitation

### ISSUE THREAD

**Issue by X-Oracle** [vfarid/v2ray-worker#21]
after some time Cloudflare says:
Worker exceeded resource limits.
and worker stops working until I redeploy it.

**Comment by GetPHP-IR** [comment]
> Worker exceeded resource limits.

upgrade your cloudflare workers free plan to paid plan

**Comment by X-Oracle** [comment]
> > Worker exceeded resource limits.
> 
> upgrade your cloudflare workers free plan to paid plan


10 bucks for one month! Not worth for only a worker.

Besides what this scrypt do is a small task and I don't think it needs that much cpu horse power.

@vfarid my man.What part of the script is consuming cpu?(I'm using worker not page)

**Comment by vfarid** [comment]
Hey,
The usual limitation is requests per day which is 100K/day.
100k requests are more than of enough for 1 user but if you use a worker for multiple users, you will touch resource limits.
The best and free solution is to create one account for each user and deploy the worker for each account separetely.

**Comment by X-Oracle** [comment]
@vfarid 
Well I know what cloudflare limits are.
And I use it for personal use and not many requests per a day.
But this happened in a fresh install!

In my further tests on a fresh cloudflare account, after configuring a password for panel, load and refreshing the sub link 5 times in a row causes it. And it will stay like that untill I go to quick edit and redeploy it.

If you were interested you could test if it is the case for you too.

Good luck

**Comment by vfarid** [comment]
It would be temporary lockdown because of cpu/resource limit. Why you need to update sub 5 time in a row when you use the script for one person?
Offcourse processing config providers` link and extracting/merging the configs will use CPU/RAM and you may face to the resource limit if you use subscription update repeatedly.
