### ISSUE TITLE
عدم آپدیت ساب اسکریشن

### ISSUE THREAD

**Issue by borhansheyn** [vfarid/v2ray-worker#22]
The SSL connection could not be established, see inner exception.

سلام ضمن تشکر ... مدتیه وقتی آپدیت ساب میزنم توی v2rang  موبایل و کامپیوتر هر دوتاش خظای بالا میاد اما به محض اینکه فیلتر شکن رایگان روشن میکنم و آپدیت میزنم آپدیتش میاد جریان چیه؟؟

**Comment by vfarid** [comment]
چند هفته‌اس که دامین worker روی بیشتر اوپراتورها فیلتر شده. نسخه‌ی ۲.۲ از این فیلترینگ اخیر عبور می‌کنه ولی خود sub رو باید با فیلترشکن آپدیت کنید بار اول. سری‌های بعد هم وقتی خود vpn وصله آپدیت کنید بعد برای تست vpn رو خاموش کنید.
