### ISSUE TITLE
جستجوی آی پی تمیز

### ISSUE THREAD

**Issue by khoja3teha** [vfarid/v2ray-worker#27]
سلام ، از دیروز انگار این قسمت کار نمیکنه ، تا دیروز اسکن میکرد آی پیارو پینگ میگرفت میداد الان نه ، میشه بررسیش کنین , ممنون

**Comment by vfarid** [comment]
این خطا رو دیروز درست کردم، به خاطر محدودیت جدید اعمال شده روی آی‌پی‌های کلادفلر بود
