### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by Graveyard9988** [vfarid/v2ray-worker#29]
درود
این ریپو هر چند ساعت اپدیت می شود و لینک های ساب سالم در آن قرار می گیرد:
https://raw.githubusercontent.com/mermeroo/V2RAY-and-CLASH-Subscription-Links/main/SUB%20LINKS

 لطفا همگام با اپدیت شدن این ریپو، لینک های ان را در کد ورکر بعدی قرار دهید تا به صورت خودکار لینک ساب های سالم در پنل ورکر هر کاربر قرار گیرد.

سپاس

**Comment by vfarid** [comment]
این امکان در کلاینت‌ها وجود نداره هنوز، وقتی امکانش ایجاد شد حتما.
