### ISSUE TITLE
کار نکردن لینک‌ ساب شخصی با کانفیگ های ویلس

### ISSUE THREAD

**Issue by qasem70** [vfarid/v2ray-worker#3]
سلام ، کد خوب کار می‌کنه ولی لینک های شخصی ویلس رو برنمی‌گرده ولی با ویمس مشکلی نداره

**Comment by vfarid** [comment]
لطفا لینک نمونه را برای بررسی در دایرکت توییترم ارسال کنید.

**Comment by vfarid** [comment]
این مشکل حل شد. کد رو میتونید از برنچ مستر بگیرید:
https://github.com/vfarid/v2ray-worker/blob/main/dist/worker.js
