### ISSUE TITLE
Anti probe

### ISSUE THREAD

**Issue by cr4zyfish** [vfarid/v2ray-worker#31]
Currently the script is not anti-probe. somebody can capture tls request and see sni. enter sni in browser and see the control panel. is it posible to move control panel to /hidden-panel ? when someone visits sni he should see an html webpage.

**Comment by vfarid** [comment]
> Currently the script is not anti-probe. somebody can capture tls request and see sni. enter sni in browser and see the control panel. is it posible to move control panel to /hidden-panel ? when someone visits sni he should see an html webpage.

KV limits in free plan prevents implementation of this feature. Assigning static path to hidden panel will have no benefit.
