### ISSUE TITLE
cloudflare error

### ISSUE THREAD

**Issue by qanoon99** [vfarid/v2ray-worker#32]
سلام وقت بخیر، از دیروز بعد از آپلود کردن فایل worker.js ، کلودفلر 86 تا ایراد ازش میگیره و نمیذاره ذخیره کنم. راهی هست؟

**Comment by vfarid** [comment]
احتمالا ناقص کپی شده، کد مشکلی برای کپی کردن نداره. جای کپی کردن، از گزینه‌ی آپلود استفاده کنید، تو ویدیو آموزشیش گفته بودم.
