### ISSUE TITLE
ویرایش نشدن پورت و tls 

### ISSUE THREAD

**Issue by csharpfarsi** [vfarid/v2ray-worker#33]
سلام تازگیا اختلال شدیدی رو کلودفلر و ورکر هاس اگه یه امکانی بذارین که بشه پورت رو به پورت های http کلود فلر تغییر بدیم و tls رو خاموش کنیم خیلی خوب میشه 
کانفیگ ها رو دونه دونه ویرایش کردنی جواب میده برا من ولی خب دونه دونه سخته

**Comment by sma-abyar** [comment]
https://github.com/sma-abyar/v2ray-worker
توی خط ۷ یه قسمت کاستوم پورت داره، اونجا یه پورت http می‌زنی که کلادفلر پشتیبانی می‌کنه، مثل ۲۰۹۵. بعد دپلوی می‌کنی روی ورکر و بعدش Update Subscription رو توی موبایلت می‌زنی و تموم می‌شه.
از لینک زیر هم می‌تونی بقیه‌ی پورت‌ها رو پیدا کنی:
https://developers.cloudflare.com/fundamentals/reference/network-ports/

**Comment by vfarid** [comment]
من زیاد موافق پروتکل http نیستم، برای رفع اختلال میتونید از fragment استفاده کنید.
