### ISSUE TITLE
مشکل اپراتور ها با vless ws

### ISSUE THREAD

**Issue by 3aeidkhalili** [vfarid/v2ray-worker#38]
سلام استاد گرامی خسته نباشید
یک هفته ای میشه روی اپراتور ایرانسل به سمت کلودفلر اختلال داریم قبلا پروتکل vless ws port 80 روی ایرانسل وصل بود اما دو هست به طور کامل قطع شده هست و حتی پنل روی ایرانسل با http بالا نمیاد اما برعکس همین ماجرا همراه اول وصل هست و پنل هم با http بالا می آید.

آیا به نظر شما این محدودیت هست یا اختلال از سمت ایرانسل ؟

اگر راه حل برای حل این مشکل دارید لطفا دریغ نکنید
باتشکر

**Comment by vfarid** [comment]
ورکر محدودیتی نداره، اختلال مربوط به ایرانسله اگه اینطور که گفتید باشه.
