### ISSUE TITLE
تعداد کانفیگ ها 

### ISSUE THREAD

**Issue by meahura** [vfarid/v2ray-worker#41]
سلام ، ای کاش تعداد کانفیگ هارو بشه توی پنل تنظیم کرد( الان ۱۰ تا خیلی زیاده برای کلودفلر و کند میشه‌) مثلا یه گزینه ای باشه بشه تنظیم کرد...تعدادشو! یا اگرم ممکن نیست  بین ۱ تا ۳ تا روی یک ورکر مشکل کندی نداره!

**Comment by vfarid** [comment]
تعداد کانفیگ‌ها هیچ ارتباطی با سرعت و کندی نداره.
