### ISSUE TITLE
عدم غیر فعال سازی فرگمنت

### ISSUE THREAD

**Issue by emad465** [vfarid/v2ray-worker#42]
سلام ، گزینه فرگمنت در پنل غیر فعال نمیشود ، یعنی اگر تیکش را برداری و سیو کنی باز هم میبینی که تیکش است و غیر فعال نمیشود

**Comment by Saleh-Mumtaz** [comment]
این مورد با ادیت کردن KV Dataset قابل حل هست، من به مشکل Worker resource limit exceeded مواجه میشم

**Comment by b3hzad1** [comment]
سلام
متاسفانه برای منم گزینه فرگمنت در پنل غیرفعال نمیشه. با ادیت کردن KV Dataset هم قابل حل نیست.
