### ISSUE TITLE
عدم ایمپورت در کلش متا یا کلش verge

### ISSUE THREAD

**Issue by Graveyard9988** [vfarid/v2ray-worker#45]
سلام
در نسخه ی جدید ورکر (امروز) ، لینک ساب کلش در کلاینت [clash meta for android (رلیز ماه قبل)](https://github.com/MetaCubeX/ClashMetaForAndroid/releases/tag/v2.10.1) و همینطور [کلش verge ویندوز (رلیز روز گذشته)](https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.5.11) ایمپورت نمی شود!
هر دو کلاینت یاد شده، از هسته متا پشتیبانی می کنند که شامل vless و ... می شود.

لینک ساب کلش این ورکر برای چه کلاینتی به کار می رود؟

تشکر

**Comment by nimashahahmadian** [comment]
برای آزمایش دسترسی لطفا لینک ورکرتون رو با مرورگر باز کنید و ببینید دیتای کانقیگ هارو بصورت بیس64 یا کلش کانفیگ میاره اگر دیتا قابل مشاهده بود یعنی مشکل از اکریپت است درصورت باز نکردن و ندیدن اطلاعات سعی کنید با فیلترشکن این کار را بکنید درصورتی که قابل مشاهده بود بار دیگر امتحان  کنید و نتیجه خود را اعلام کنید.
