### ISSUE TITLE
تایم آوت کانفیگ

### ISSUE THREAD

**Issue by eenjavi** [vfarid/v2ray-worker#46]
سلام مهندس ورکر نصب شده تعدادی کانفیگ آورده اما بیش از 90 درصد آنها تایم آوت می دهند

**Comment by Camileccc** [comment]
部署worker失败。。。。

**Comment by vfarid** [comment]
طبیعت این کد همینه. همیشه فقط بخشی از کانفیگ‌ها کار میکنن.
