### ISSUE TITLE
باز نشدن سایت های پشت کلادفلر با کانفیگ‌های اصلی

### ISSUE THREAD

**Issue by Alireza-Kazemifard** [vfarid/v2ray-worker#48]
کانفیگ‌های اصلی Built-in VLESS در چند روز اول بعد از اپدیت ۲.۳ سایت های پشت کلادفلر را باز میکرد اما بعد از گذشت چند روز دوباره مثل ورژن های گذشته worker هیچ کدام از سایت های پشت کلاد فلر را باز نمیکند.

**Comment by emad465** [comment]
آره دقیقا برای منم همینطوره باز نمیکنه

**Comment by vfarid** [comment]
مشکل به خاطر از کار افتادن پراکسی پیش فرض کد بود که می شد از طریق پنل تغییرش داد. این مشکل رو تو نسخه ۲.۴ تا حد زیادی حل کردم.
