### ISSUE TITLE
error 1101

### ISSUE THREAD

**Issue by tesinstas** [vfarid/v2ray-worker#5]
با سلام،Error 1101 رو میگیرم
(( وقتی به لینک ساب یا کلش وارد میشم ))

![IMG_20230902_055102_154](https://github.com/vfarid/v2ray-worker/assets/142853851/94153c46-50cd-471d-ad17-86686007853b)

**Comment by vfarid** [comment]
این کد بد کپی شده بوده. لطفا با دقت و مطابق ویدیوی آموزشی انجام بدید.
