### ISSUE TITLE
انتخاب کشور

### ISSUE THREAD

**Issue by alimahmoudnia** [vfarid/v2ray-worker#50]
سلام خسته نباشید بابت تمام زحمتاتون می خاستم بگم اگر امکان انتخاب کشور وجود داشت مخصوصا آمریکا چه در پنل و چه به صورت اسم روی هر کانفیگ خیلی امکان خوبی بود. چون همونطور که درجریانید یکسری سرویس ها در صورت مغایرت کشور کاربر هایرو مسدود میکنن و فقط به بعضی کشور ها سرویس ارایه می دن.

**Comment by Hggguu7** [comment]
[Uploading Microsoft Privacy Statement – Microsoft privacy.pdf…]()

**Comment by Surfboardv2ray** [comment]
> سلام خسته نباشید بابت تمام زحمتاتون می خاستم بگم اگر امکان انتخاب کشور وجود داشت مخصوصا آمریکا چه در پنل و چه به صورت اسم روی هر کانفیگ خیلی امکان خوبی بود. چون همونطور که درجریانید یکسری سرویس ها در صورت مغایرت کشور کاربر هایرو مسدود میکنن و فقط به بعضی کشور ها سرویس ارایه می دن.

برای این نیاز هست که قبل تبدیل کانفیگ‌ها به کانفیگ پشت کلادفلیر، نام کشور از آدرس کانفیگ گرفته بشه، تا زمان اضافه شدن این قابلیت میتونید از [این تامین کننده](https://raw.githubusercontent.com/Surfboardv2ray/Proxy-sorter/main/ws_tls/proxies/wstls_base64) در لیست پنل استفاده کنید که همین کار رو انجام داده، یا با محدودیت مصرف عمومی از لینک های [این رپو](https://github.com/Surfboardv2ray/Vfarid-fix)  استفاده کنید.

**Comment by vfarid** [comment]
این امکان رو در نسخه ۲.۴ برای کانفیگ‌های داخلی Built-in اضافه کردم.
