### ISSUE TITLE
Trojan nodes obtained by subscription dont work properly

### ISSUE THREAD

**Issue by techiewmvp** [vfarid/v2ray-worker#65]
Trojan node that obtained by subscription dosent work properly，test true connection turns out -1，got log from V2rayN :  “proxy/trojan: failed to find an available destination” , so i checked trojan protocol setting ，i find that the path “/” doesnt match with the code ，in the workers.js the code is “path: "trojan-ws/?ed=2048",” change the path “/” to “trojan-ws/?ed=2048” in V2rayN client these Trojan nodes work properly.

**Comment by vfarid** [comment]
I didnt get your point. both path you wrote are the same. I belive trojan configs have dns issue which should be resolved and it is not related to the `path`.
