### ISSUE TITLE
فایل json

### ISSUE THREAD

**Issue by CyrusTheV** [vfarid/v2ray-worker#66]
درود
با تشکر از زحمات فراوان شما.
برای اینکه بشه ساب رو مستقیم به SB ادد کرد کانکشنها باید بصورت json نمایش داده بشن. BPB اینکار رو انجام داده اما با توجه به اینکه شما گفتید اررور ها بسیار کمتر شدن میخواستم با ورکر شما یه تستی بزنم و ببینم نسبت به BPB  کمتره یا نه که اگه اینطور باشه بریم برای رفع ایرادات BPB.

**Comment by vfarid** [comment]
اگه منظور خروجی json برای کاستوم کانفیگ هست فعلا اضافه نکردم ولی فرصت کنم بعدا اضافه می‌کنم. اون بخشی که گفتم باعث کاهش خطای کانفیگ‌های داخلی ورکر شده تغییراتش تو روش انتخاب proxyip و نوع هندل کردن خطاها هست. میتونید فانکشن HandleTCPOutbound  رو تو فایل vless.ts ببینید و تغییراتشو مقایسه کنید.

**Comment by CyrusTheV** [comment]
فعلا کارمو با این https://github.com/tindy2013/subconverter راه انداختم.مرسی
