### ISSUE TITLE
مشکل در تلگرام

### ISSUE THREAD

**Issue by alifallahrn** [vfarid/v2ray-worker#67]
سلام، خسته نباشید
من از نسخه جدید ورکر استفاده کردم، دوتا مشکل عجیب دارم که تو نسخه های قبلی همچین مشکلی نبود
اول اینکه روی اپراتور همراه اول کانفیگ ها اغلب کار نمیکنن و دوم اینکه روی اکثر اپ ها اوکیه ولی روی تلگرام Connecting باقی میمونه و متصل نمیشه
ممنون میشم راهنمایی کنید و اگر کانفیگ خاصی باید اعمال کنم بهم بگید

**Comment by vfarid** [comment]
به خاطر اختلال اینترنت تو روزهای اخیره ارتباطی با آپدیت اخیر نداره. تو آپدیت اخیر همونطور که نوشتم فقط یه سری کانفیگ اضافه شده و proxyip هم اتوماتیک شده تا بتونه سایتای پشت کلادفلر رو باز کنه.
