### ISSUE TITLE
عدم اتصال به تلگرام

### ISSUE THREAD

**Issue by Behnamjef** [vfarid/v2ray-worker#70]
سلام. خیلی ممنون بابت زحماتی که میکشین.
دوتا مسئله:
1. از دیروز متاسفانه تلگرام لود نمیشه. ممنون میشم اگه راهکاری هست راهنمایی کنین.
2. آموزش setup روی گیت‌هاب اگه هست ممنون میشم به اشتراک بذارین.

**Comment by Behnamjef** [comment]
> [#67 (comment)](https://github.com/vfarid/v2ray-worker/issues/67#issuecomment-2145653488)

یعنی منتظر بمونیم؟

**Comment by vfarid** [comment]
مشکلی وجود نداره که درست کنم. تلگرام هم مثل سایر اپ‌ها باز میشه شاید به تلگرام پراکسی دادید که باز نمیشه و مشکل از پراکسیه. تلگرام حتی با کانفیگ‌های trojan که مشکل dns دارن هم باز میشه.
