### ISSUE TITLE
The workflow is not valid. .github/workflows/deploy.yml (Line: 31, Col: 7): Unexpected value 'with'

### ISSUE THREAD

**Issue by joy4theluv** [vfarid/v2ray-worker#72]
Hi! I would like to get any suggestions on this problem.
![image](https://github.com/vfarid/v2ray-worker/assets/71491462/5feca2ee-30c3-4ebd-9a39-3e53848418e9)

**Comment by 404area** [comment]
I have the same problem

**Comment by mehdico** [comment]
@404area @joy4theluv 
I fixed this in [my repo](https://github.com/mehdico/v2ray-worker).

**Comment by vfarid** [comment]
https://github.com/vfarid/v2ray-worker/pull/74
